# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-taot

# >> macros
%define __requires_exclude ^libQt5SystemInfo.*$
%define __provides_exclude_from ^%{_datadir}/.*$
# << macros
